---
name: nio4r
package: Dependabot Api
licenses:
    - text: "Copyright (c) <year> <owner> \n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n\n1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
    - text: |-
        MIT License

        Copyright (c) <year> <copyright holders>

        Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
    - text: |-
        (c) 2009-2015,2018-2020 Marc Alexander Lehmann <libecb@schmorp.de>
        (c) 2011 Emanuele Giaquinta
        Copyright (c) 2007-2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007-2020 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011,2012,2013 Marc Alexander Lehmann
        Copyright (c) 2007,2008,2009,2010,2011,2012,2013,2016,2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011,2012,2013,2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011,2016,2017,2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011,2016,2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2007,2008,2009,2010,2011,2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2011 Tony Arcieri
        Copyright (c) 2011-2017 Tony Arcieri
        Copyright (c) 2019 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright (c) 2019-2020 Marc Alexander Lehmann <libev@schmorp.de>
        Copyright, 2007-2019, by Marc Alexander Lehmann
        Copyright, 2011-2017, by Tony Arcieri
        Copyright, 2011-2018, by Tony Arcieri
        Copyright, 2011-2020, by Tony Arcieri
        Copyright, 2012, by Bernd Ahlers
        Copyright, 2012, by Dirkjan Bussink
        Copyright, 2012, by Logan Bowers
        Copyright, 2013, by Luis Lavena
        Copyright, 2013, by Per Lundberg
        Copyright, 2013, by Ravil Bayramgalin
        Copyright, 2013, by Sadayuki Furuhashi
        Copyright, 2013, by Shannon Skipper
        Copyright, 2013, by Stephen von Takach
        Copyright, 2013, by Tim Carey-Smith
        Copyright, 2014, by Anatol Pomozov
        Copyright, 2014, by Hiroshi Shibata
        Copyright, 2014, by John Thornton
        Copyright, 2014, by Marek Kowalcze
        Copyright, 2014, by Sergey Avseyev
        Copyright, 2015-2016, by Upekshe Jayasekera
        Copyright, 2015-2017, by Tiago Cardoso
        Copyright, 2015, by Daniel Berger
        Copyright, 2015, by Upekshe Jayasekera
        Copyright, 2015, by Vladimir Kochnev
        Copyright, 2016-2017, by Tony Arcieri
        Copyright, 2016-2018, by Jun Aruga
        Copyright, 2016-2021, by Olle Jonsson
        Copyright, 2016, by Denis Washington
        Copyright, 2016, by Omer Katz
        Copyright, 2016, by Upekshe Jayasekera
        Copyright, 2017-2022, by Gregory Longtin
        Copyright, 2017, by Jun Aruga
        Copyright, 2017, by Lars Kanis
        Copyright, 2017, by Tao Luo
        Copyright, 2017, by Tomoya Ishida
        Copyright, 2017, by Usaku Nakamura
        Copyright, 2018-2023, by Samuel Williams
        Copyright, 2018-2024, by Samuel Williams
        Copyright, 2019-2020, by Benoit Daloze
        Copyright, 2019-2020, by Gregory Longtin
        Copyright, 2019-2023, by Samuel Williams
        Copyright, 2019, by Cedric Boutillier
        Copyright, 2019, by Jesus Burgos Macia
        Copyright, 2019, by Orien Madgwick
        Copyright, 2019, by Thomas Kuntz
        Copyright, 2019, by Zhang Kang
        Copyright, 2020-2021, by Joao Fernandes
        Copyright, 2020, by Boaz Segev
        Copyright, 2020, by Charles Oliver Nutter
        Copyright, 2020, by Elad Eyal
        Copyright, 2020, by Gregory Longtin
        Copyright, 2020, by Joao Fernandes
        Copyright, 2020, by Pedro Paiva
        Copyright, 2020, by Thomas Dziedzic
        Copyright, 2021, by Jeffrey Martin
        Copyright, 2021, by Jun Jiang
        Copyright, 2021, by Pavel Lobashov
        Copyright, 2023-2024, by Pavel Rosicky
        Copyright, 2023-2024, by Vit Ondruch
        Copyright, 2023, by Jean Boussier
        Copyright, 2023, by Maxime Demolin
        Copyright, 2023, by Phillip Aldridge
        Copyright, 2023, by Samuel Williams
        Copyright, 2023, by Tsimnuj Hawj
